### ISSUE TITLE
[FEAT] Change setcap to make Bluetooth dongles work

### ISSUE THREAD

**Issue by johan12345** [linuxserver/docker-homeassistant#86]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

```
setcap 'cap_net_raw,cap_net_admin+eip' /usr/bin/python3.11
```
needs to be executed before starting Home Assistant.

### Reason for change

This is necessary to make the [Bluetooth integration](https://www.home-assistant.io/integrations/bluetooth/) or the [ble_monitor custom component](https://github.com/custom-components/ble_monitor) work. See [this FAQ](https://custom-components.github.io/ble_monitor/faq#i-get-a-permissionerror-in-home-assistant-after-the-installation-or-python-upgrade). Without the change, I am getting an error

> HCIdump thread: Something wrong - interface hci0 not ready, and will be skipped for current scan period.

in the Home Assistant logs.

### Proposed code change

Replace 
```
setcap 'cap_net_bind_service=+ep' /usr/bin/python3.11
```
with
```
setcap 'cap_net_bind_service=+ep,cap_net_raw,cap_net_admin+eip' /usr/bin/python3.11
```
needs to be executed before starting Home Assistant.

in [/etc/s6-overlay/s6-rc.d/svc-homeassistant/run](https://github.com/linuxserver/docker-homeassistant/blob/7185b59489963b21592945fb10b10977db4fb4a1/root/etc/s6-overlay/s6-rc.d/svc-homeassistant/run).

**Comment by a13xie** [comment]
@johan12345 You are a godsent, I spend a good few hours trying to figure out why Bluetooth wasn't working on my server. Thank you so much!

**Comment by webysther** [comment]
> @johan12345 You are a godsent, I spend a good few hours trying to figure out why Bluetooth wasn't working on my server. Thank you so much!

You fixed build a new image?

**Comment by aptalca** [comment]
I keep forgetting about this. Sorry about that.

I personally use bt proxy with an esp32 and my HA server doesn't have bt. So I'll likely need some testing by you guys. I'll ping you here when I have a dev build.

**Comment by webysther** [comment]
> I keep forgetting about this. Sorry about that.
> 
> I personally use bt proxy with an esp32 and my HA server doesn't have bt. So I'll likely need some testing by you guys. I'll ping you here when I have a dev build.

No problem, I can test to you, just ping me here (discord I don't access often)

**Comment by aptalca** [comment]
@webysther @johan12345 @a13xie 

Alright, so there is one issue. Setting the caps `cap_net_raw` and `cap_net_admin` for the python binary does not work when the container itself does not have those capabilities added. One would have to add those to the docker arguments specifically.

I'd rather not add it to the readme for everyone because 1. Most people don't need it and 2. The more arguments we add, the more confusing it becomes to the users and the more support requests they generate.

I'm also not sure if adding the caps to the binary is absolutely necessary. Perhaps setting those for the container is sufficient?

Can you try running the container with those two caps added to the container and see if bt works? You would also have to have bluez installed on host and the dbus socket mapped (`/run/dbus` or `/var/run/dbus`, whichever your host uses)
Docker cli: `--cap-add=NET_ADMIN --cap-add=NET_RAW`
Compose:
```
    cap_add:
      - NET_ADMIN
      - NET_RAW
```

If that works, nothing further is needed, perhaps a readme note. If that doesn't work, I'll have to come up with a dynamic way to add the caps to the binary, which will require some work on how to properly detect bt usage, hopefully without user input.

Thanks

**Comment by a13xie** [comment]
@aptalca You're right, I was not able to start HASS after only changing the binary caps.

It seems adding caps to the container is enough tho.

I'll leave the binary alone and just keep the caps added to the container. My thermometer is connecting as expected this way.

**Comment by aptalca** [comment]
Sounds good. Thanks for the test. I'll update the readme about the caps.

**Comment by webysther** [comment]
@aptalca in my case after restart the server the connection start working, just for everyone that find this issue:

- On debian based (ubuntu server in my case):

```sh
sudo apt-get -y install dbus-broker bluez
```

- Restart the server
- Add:

```yml
...
    volumes:
      - config:/config
      - /run/dbus:/run/dbus:ro
...
```

- No cap is needed
